### PR TITLE
Move EraParser from Wikibase.git to DataValues Time

### PR DESCRIPTION
**Pull request by thiemowmde**
* I moved the two files in commit 1 without changing anything.
* Commit 2 is my rewrite.

### CODE REVIEW

**Comment by addshore** [comment]
I'm not a great fan of passing the string by reference in some of the methods introduced in this patch.
Could the methods not simply return an array of values?
array($era, $changedValue) ?

**Comment by thiemowmde** [comment]
That was actually very straight-forward. See commit 3. Thanks for the suggestion.

**Comment by addshore** [comment]
Lovely! Thanks for doing that, less likely to confuse now!
Scrutinizer tests are again nothing to do with this change....

Needs a rebase! Otherwise I would merge

**Comment by thiemowmde** [comment]
Rebased.

**Pull request merged**
