### PR TITLE
Correct calendar model documentation

### PR DESCRIPTION
**Pull request by thiemowmde**
This documents how we are doing it **now**. Therefor I suggest to merge this, no matter what the outcome of the discussion at [T88437](https://phabricator.wikimedia.org/T88437) is. If the outcome of the discussion is different, we can change this again. But as it is now is wrong, no matter what.

Bug: [T88438](https://phabricator.wikimedia.org/T88438)

### CODE REVIEW

**Comment by thiemowmde** [comment]
I did a major update of this patch, reflecting the outcome of the discussion(s). It's still documentation only and does not change any behavior.

Pinging @Jc3s5h.

**Comment by Jc3s5h** [comment]
This is rather sparse documentation, but it seems to cover the essential points. Of course, the documentation doesn't count unless it is made available to the data users.

A disadvantage of this approach is that data users will have to write (or at least extensively test) any existing date parsers because this is a unique format that no on else uses. I will take a look at the user documentation and try to understand if a change to the existing user-oriented documentation will only affect Wikidata, or if there are other users of the user-oriented documentation and the documentation will have to be forked.

**Comment by thiemowmde** [comment]
> This is rather sparse documentation

On purpose, since this class shouldn't even care about the format but currently does. The format validation must be moved to a validator.

> A disadvantage of this approach

What approach (in contrast to what other approach) are you referring to?

> this is a unique format that no on else uses.

To what format are you referring to? "Unique" in which way? It's modeled after ISO to avoid exactly that, to be able to use existing parsers (to an extend).

> I will take a look at the user documentation

To what "user documentation" (in contrast to what other documentation) are you referring to?

> the documentation will have to be forked.

??????????

**Comment by Jc3s5h** [comment]
Let's start from the beginning. Wikipedia has human readers, and information there does not follow rigid formats, but rather can only be understood by human readers (for the most part). Wikidata is a database, which is mostly intended to have data extracted by computers outside the Wikimedia Foundation for use in an automated way. Therefore the format of the data must be specified and the specification made available to everyone so their automated processes can parse the data.

There may be some pre-existing ISO 8601 parsers that can parse our current de facto format, but there are some requrements in ISO 8601 which parsers are entitled to presume will be true of the input to the parsers, but are not true of our format. They are entitled to presume that there are a fixed number of digits in the year, and that fixed number (but the method of supplying the fixed number of digits to the parser is not part of the ISO 8601 specification). Our format does not have a fixed number of digits in the year. The parser is entitled to presume the date is a Gregorian calendar date; the parser user could order the parser to convert the date to Julian, but if that were done to some of our dates, there would be a double conversion. The parser is entitled to presume that neither the date nor the month will ever be "00". The parser is entitled to presume "Z" is a valid time zone indicator. None of these are true of our format.

The nearest we have to a notice to data users about what the data format is is https://www.mediawiki.org/wiki/Wikibase/DataModel

If we took the approach of always storing Gregorian calendar dates with a fixed number of digits in the year, and left conversion (if desired) to the data user, we would be able to rigorously obey ISO 8601, so if a parser failed to parse it correctly, it would be the fault of whoever wrote the parser, not our fault.

**Comment by thiemowmde** [comment]
@Jc3s5h, please don't get me wrong, but this is a concrete patch that solves the concrete problem of outdated code documentation. Based on your comment I can't improve the code further. It does what it does: describing what the class does. Longer discussions about fundamental problems should happen in Phabricator, they will not have impact here.

**Pull request merged**
